### ISSUE TITLE
"daemon" directive is duplicate

### ISSUE THREAD

**Issue by trondhindenes** [weareinteractive/ansible-nginx#4]
I'm getting this error on Ubuntu 14.04:

2015/05/25 13:08:32 [emerg] 18720#0: "daemon" directive is duplicate in /etc/nginx/nginx.conf:17

Commenting out line 17:
 # Determines whether nginx should become a daemon
#daemon {{ nginx_daemon }};

Seems to resolve the issue.

**Comment by franklinkim** [comment]
Right, thanks! Fixed this with 830eabb9b348800651fb8a2d525e64118519ae20
