### ISSUE TITLE
Overriding site template file

### ISSUE THREAD

**Issue by timka** [weareinteractive/ansible-nginx#6]
How does template lookup find the site config template specified as `item.template`? Where do I put it? Putting in the playbook file's directory doesn't work neither does `templates` subdir there.

AFAIU, the approach suggested [here](https://groups.google.com/forum/#!topic/ansible-project/9xRyYIOdSro) suggests creating a local role w/ the same name that contains only the template file, but this seems to override the tasks as well resulting in an empty local role.

**Comment by franklinkim** [comment]
Hi, the template is being copied via the [template module](http://docs.ansible.com/ansible/template_module.html):

> `src`: Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.

so for sth like this:

```
project/
  roles/
    franklinkim.nginx/
  templates/
    my-custom-template.j2
```

if you're running the command from the `project` dir, the relative path would look like:

```yaml
  ...
  nginx_sites:
      - id: my-site
        template: templates/my-custom-template.j2
  ...
```

hope that helps.

**Comment by timka** [comment]
Thanks for the reply!

I ended up placing the template in `project/my-custom-template.j2`.

For some reason `templates/my-custom-template.j2` didn't work for me, that's why I opened the issue. Maybe it has something to do with my role_path. I add galaxy roles to `project/deps`. Not the best option but can live with that as it's not critical. May investigate that further later.
